### ISSUE TITLE
CTRL+click on mac 

### ISSUE THREAD

**Issue by MariaBarrett** [boberle/sacr#1]
I started using the tool and have found most functions working on my mac.
I can't, however, link distant mentions that are so far away that they are not visible on the same screen (without scrolling) even when zooming out. CTRL+click is system-wide linked to right-click on macs. I tried different combinations of option, ctrl and command with no luck. 
Thanks,

**Comment by boberle** [comment]
I guess it's way too late for you, but for future reference, I just got access to a Mac and at last solved the issue by making it possible to use the Command key instead of the Ctrl key for all shortcuts.
