### ISSUE TITLE
convert output format

### ISSUE THREAD

**Issue by fairy-of-9** [boberle/sacr#2]
Hi,

In the paper, it is written that it provides scripts for easily parsing annotation results.
```
Such scripts exist for example to convert to and from the Glozz format (Widlöcher and Mathet, 2012) 
(a format in which annotations are deported and that can be imported in tools such as Analec or TXM) or the CONLL2011 format.
```
But I haven't found the scripts yet.
Is there anything I missed?

Thanks!

**Comment by boberle** [comment]
Hi,

Conversion scripts are in my other repository: https://github.com/boberle/corefconversion.

The repo doesn't contain the script specifically for the Glozz format, but I can publish it if you need it (I think it is written in Perl, though).

Hope that helps

**Comment by boberle** [comment]
Sorry, I just realized that I was wrong in my last comment. The scripts to convert between SACR and Glozz (in any direction) are here: https://boberle.com/projects/coreference-annotation-with-sacr/. They are in Perl but you can make the conversion online.

**Comment by fairy-of-9** [comment]
Thanks!
